version: '3'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - LLAMAEDGE_URL=http://host.docker.internal:8080/v1
      - LLAMAEDGE_MODEL=Qwen2.5-Coder-3B-Instruct
      - LLAMAEDGE_EMBED_MODEL=gte-Qwen2-1.5B-instruct
      - CARGO_PATH=/root/.cargo/bin/cargo
      - RUST_COMPILER_PATH=/root/.cargo/bin/rustc
    volumes:
      - ./output:/app/output
      - ./data:/app/data
      - ./templates:/app/templates
    extra_hosts:
      - "host.docker.internal:host-gateway"