version: '3'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT_API_KEY=${QDRANT_API_KEY:-qdrant_placeholder_key}

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_API_KEY=${QDRANT_API_KEY:-qdrant_placeholder_key}
      - LLM_API_BASE=http://host.docker.internal:8080/v1
      - LLM_MODEL=Qwen2.5-Coder-3B-Instruct
      - LLM_EMBED_MODEL=gte-Qwen2-1.5B-instruct
      - LLM_API_KEY=${LLM_API_KEY:-your_llm_api_key_here}
      - CARGO_PATH=/root/.cargo/bin/cargo
      - RUST_COMPILER_PATH=/root/.cargo/bin/rustc
    volumes:
      - ./output:/app/output
      - ./data:/app/data