services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_BASE=http://host.docker.internal:8080/v1
      - LLM_MODEL=Qwen2.5-Coder-3B-Instruct-Q5_K_M
      - LLM_EMBED_MODEL=local-embed
      - LLM_EMBED_SIZE=768
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - qdrant

  mcp-server:
    build: .
    command: openmcp run -p 0.0.0.0:3000 -- python app/mcp_tools.py
    ports:
      - "3000:3000"
    environment:
      - API_HOST=api        # Use service name within Docker network
      - API_PORT=8000
      - MCP_TRANSPORT=sse
    depends_on:
      - api

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - AUTH_DISABLED=true
