version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_BASE=${LLM_API_BASE:-http://localhost:8080/v1}
      - LLM_MODEL=${LLM_MODEL:-Qwen2.5-Coder-3B-Instruct}
      - LLM_EMBED_MODEL=${LLM_EMBED_MODEL:-gte-Qwen2-1.5B-instruct}
      - LLM_EMBED_SIZE=${LLM_EMBED_SIZE:-1536}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mcp-server:
    build: .
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_BASE=${LLM_API_BASE:-http://localhost:8080/v1}
      - LLM_MODEL=${LLM_MODEL:-Qwen2.5-Coder-3B-Instruct}
      - LLM_EMBED_MODEL=${LLM_EMBED_MODEL:-gte-Qwen2-1.5B-instruct}
      - LLM_EMBED_SIZE=${LLM_EMBED_SIZE:-1536}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    command: python -m app.mcp_server
    
  mcp-proxy:
    image: sparfenyuk/mcp-proxy:latest
    ports:
      - "3000:3000"
    volumes:
      - ./mcp-proxy-config.json:/app/mcp-proxy-config.json
    depends_on:
      - mcp-server
      
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage